# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BBC', models.CharField(max_length=200)),
                ('CNN', models.CharField(max_length=200)),
                ('aljazeera', models.CharField(max_length=200)),
                ('fox', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
